project/accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('profile/', profile, name='users-profile'),
    path('password_change/', ChangePasswordView.as_view(), name='password_change'),

]

project/main_app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'main_app'

urlpatterns = [
    path('main/', main_page, name='main'),
    path('load_file/', load_file, name='load_file'),
    path('logs_file/<slug:file_slug>/', logs_file, name='logs_file'),
    path('update_file/<slug:file_slug>/', update_file, name='update_file'),
    path('update_file/<slug:file_slug>/<str:delete>/', update_file, name='delete_file')


]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("accounts/", include("accounts.urls"), name='accounts'),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main_app/models.py
from django.db import models
from django.urls import reverse

from accounts.models import User


# Create your models here.

class File(models.Model):
    class Status(models.TextChoices):
        NEW = 'NEW', 'New'
        UPDATED = 'UPD', 'Updated'
        CHECKED = 'CHK', 'Checked'

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    name = models.CharField(max_length=250, unique=True, verbose_name='Имя файла')
    description = models.TextField(blank=True, verbose_name='Описание')
    file = models.FileField(upload_to='files', verbose_name='Файл')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    status = models.CharField(max_length=3, choices=Status.choices, default=Status.NEW, verbose_name='Статус')
    slug = models.SlugField(max_length=250, unique_for_date='created', db_index=True, verbose_name='Слаг')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Файлы'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main_app:update_file', args=[self.slug])


class Log(models.Model):
    file = models.ForeignKey(File, on_delete=models.CASCADE, verbose_name='Файл')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    description = models.TextField(default='Файл успешно проверен')
    send = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Логи'
        verbose_name_plural = 'Логи'

project/main_app/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class LoadFileForm(forms.ModelForm):
    name = forms.CharField(max_length=250, widget=forms.TextInput(
        attrs={"class": "form-control mb-1"}), label='Название файла')
    description = forms.CharField(widget=forms.Textarea(
        attrs={"class": "form-control mb-1"}), label='Описание файла')
    file = forms.FileField(widget=forms.FileInput(attrs={"class": "form-control mb-1"}),
                                label='Файл')

    def clean_file(self):
        data = self.cleaned_data['file']

        # check if the content type is what we expect
        content_type = data.content_type
        print(content_type)
        if content_type == 'text/x-python':
            return data
        else:
            raise ValidationError('Неправильное расширение файла. Файл должен быть формата .py')

    class Meta:
        model = File
        fields = ['name', 'description', 'file']

project/main_app/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.shortcuts import render
from slug import slug

from .forms import LoadFileForm
from .models import File


# Create your views here.
@login_required
def main_page(request):
    files = File.objects.filter(author_id=request.user.id).order_by('-updated', '-created')
    paginator = Paginator(files, 3)
    page_number = request.GET.get('page', 1)
    files = paginator.get_page(page_number)
    return render(request, 'main_app/main_page.html', context={'files': files})


@login_required
def load_file(request):
    if request.method == 'POST':
        fileform = LoadFileForm(request.POST, request.FILES)
        if fileform.is_valid():
            file = fileform.save(commit=False)
            file.author = request.user
            file.slug = slug(file.name)
            file.save()
            messages.success(request, f'Пользователь {file.author.username} успешно загрузил файл')
            return redirect('/main/')
    else:
        fileform = LoadFileForm()

    return render(request, 'main_app/load_file.html', context={'fileform': fileform})


@login_required
def update_file(request, file_slug, delete=False):
    file = File.objects.get(slug=file_slug)
    if not delete:
        if request.method == 'POST':
            fileform = LoadFileForm(request.POST, request.FILES, instance=file)
            if fileform.is_valid():
                file = fileform.save(commit=False)
                file.status = File.Status.UPDATED
                file.save()
                messages.success(request, f'Пользователь {file.author.username} успешно обновил файл')
                return redirect('/main/')
        else:
            fileform = LoadFileForm(instance=file)
    else:
        messages.success(request, f'Пользователь {file.author.username} успешно удалил файл - {file.name}')
        file.delete()
        return redirect('/main/')
    return render(request, 'main_app/load_file.html', context={'fileform': fileform})


@login_required
def logs_file(request, file_slug):
    file = File.objects.get(slug=file_slug)
    logs = file.log_set.all()
    paginator = Paginator(logs, 3)
    page_number = request.GET.get('page', 1)
    logs = paginator.get_page(page_number)

    return render(request, 'main_app/logs_file.html', context={'file': file, 'logs': logs})

project/templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
{% load file_tags %}
<html style="min-height: 100vh;
  overflow: auto;">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body style="min-height: 100vh;
  overflow: auto;">
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color: #A9A9A9;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main_app:main' %}">Главная</a>
    <div class="d-grid gap-2">
        <a class="btn btn-primary" type="button" href="{% url 'main_app:load_file' %}">Загрузить файл</a>
    </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:users-profile' %}"><img
                            class="rounded-circle" width="30" src="{{ user.profile.avatar.url }}"/> {{ user.username }}
                    </a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Выйти</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Войти</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endif %}
<div class="container" style="padding-top: 6rem; min-height: 100vh;">
    {% block auth %}
    {% endblock %}
    <div class="row">
        <div class="col-lg-8">
            {% if user.is_authenticated %}
                {% block message %}
                {% for message in messages %}
                    <div class="container d-flex align-items-center justify-content-center">
                        <div class="alert alert-warning alert-dismissible fade show w-50  d-block" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
                        </div>
                    </div>
                {% endfor %}
                {% endblock %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
    {% if user.is_authenticated %}
        {% block tags %}
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">Проверенные файлы</div>
                <div class="card-body">
                    Количество: {% total_files_checked %}
                </div>
            </div>
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header">Непроверенные файлы</div>
                <div class="card-body">
                    Количество: {% total_files_unchecked %}
                </div>
            </div>
        </div>
        {% endblock %}
    {% endif %}
    </div>
    </div>
</div>
{% block pagin %}
{% endblock %}
<footer class="py-2 mt-2" style="background-color: #A9A9A9">
    <div class="container"><p class="m-0 text-center text-black">Copyright &copy; 2023 Powered by
        Django</p></div>
</footer>
</body>
</html>

project/templates/main_app/load_file.html
{% extends 'main_app/base.html' %}
{% block title %} Главная {% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {% for field in fileform %}
            <div>
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <br><input type="submit" class="btn btn-primary btn-lg" value="Загрузить">
    </form>
{% endblock %}

project/templates/main_app/logs_file.html
{% extends 'main_app/base.html' %}
{% load file_tags %}
{% block title %} Отчет {% endblock %}
{% block content %}
    <h1 style="text-align: center">Отчет по файлу: {{ file.name }}</h1>
    <h2 style="text-align: center">{{ file.file.name|slice:'6::' }}</h2>
    {% for log in logs %}
         <div class="card">
             <div class="card-body">
                 <h5 class="card-title">{{ forloop.counter }}. {{ log.created }}</h5>
                 <p class="card-text">{{ log.description }}</p>
             </div>
         </div><br>
    {% endfor %}
{% endblock %}
{% block tags %}
    <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">Логи</div>
                <div class="card-body">
                    Количество: {% total_logs file.slug %}
                </div>
            </div>
    </div>
{% endblock %}
{% block pagin %}
{% include 'main_app/pagination.html' with page=logs %}
{% endblock %}

project/templates/main_app/main_page.html
{% extends 'main_app/base.html' %}
{% block title %} Главная {% endblock %}
{% block content %}
    {% for file in files %}
    <div class="col">
        <div class="card">
            <div class="card-header">
                {{ file.name }}
                {% if file.status == 'CHK' %}
                <span style="float: right">&#9989;</span>
                {% else %}
                <span style="float: right">&#9203;</span>
                {% endif %}
              </div>
            <div class="card-body">
                <h5 class="card-title">{{ file.file.name|slice:'6::' }}</h5>
                <p class="card-text">{{ file.description }}</p>
                <a href="{% url 'main_app:update_file' file_slug=file.slug %}" class="btn btn-primary">Обновить</a>
                <a href="{% url 'main_app:delete_file' file_slug=file.slug delete=True %}" class="btn btn-danger">Удалить</a>
                <a href="{% url 'main_app:logs_file' file_slug=file.slug %}" class="btn btn-secondary">Отчет</a>
              </div>
            <div class="card-footer text-muted">
                Дата загрузки:
                {{ file.created }}
                <span style="float: right">
                    {% if file.status == 'UPD' %}
                            Дата обновления:
                            {{ file.updated }}
                    {% endif %}
                </span>
              </div>
        </div><br>
    </div>
    {% endfor %}
{% endblock %}
{% block pagin%}
{% include 'main_app/pagination.html' with page=files %}
{% endblock %}

project/templates/main_app/pagination.html
{% if page.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ 1 }}" aria-label="First">
                <span aria-hidden="true"><<</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true"><</span>
            </a>
        </li>
        {% endif %}
        {% for p in page.paginator.page_range %}
        {% if p >= page.number|add:-2 and p <= page.number|add:2 %}
        <li class="page-item {% if page.number == p %}active{% endif %}">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item">
            {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">></span>
                {% endif %}
            </a>
        </li>
        <li class="page-item">
            {% if page.number != paginator.num_pages %}
            <a class="page-link" href="?page={{ paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">>></span>
                {% endif %}
            </a>
        </li>
    </ul>
</nav>
{% endif %}